//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelPreGeneratedOutput
    {
        public string TransactionId { get; set; }
        public int OutputNumber { get; set; }
        public long Amount { get; set; }
        public string PrivateKey { get; set; }
        public int Consumed { get; set; }
        public string Script { get; set; }
        public string AssetId { get; set; }
        public string Address { get; set; }
        public string Network { get; set; }
        public byte[] Version { get; set; }
    }
}
