//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelCoin
    {
        public long Id { get; set; }
        public string TransactionId { get; set; }
        public int OutputNumber { get; set; }
        public long ReservedForChannel { get; set; }
        public Nullable<bool> ReservationFinalized { get; set; }
        public Nullable<bool> ReservationTimedout { get; set; }
        public System.DateTime ReservationCreationDate { get; set; }
        public string ReservedForMultisig { get; set; }
        public byte[] Version { get; set; }
        public System.DateTime ReservationEndDate { get; set; }
    
        public virtual OffchainChannel OffchainChannel { get; set; }
    }
}
