//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRequest
    {
        public string WalletAddress01 { get; set; }
        public string WalletAddress02 { get; set; }
        public string Asset01 { get; set; }
        public string Asset02 { get; set; }
        public Nullable<int> Amount01 { get; set; }
        public Nullable<int> Amount02 { get; set; }
        public string ServiceTransactionId { get; set; }
        public string ExchangeId { get; set; }
        public Nullable<int> FirstClientSigned { get; set; }
        public Nullable<int> SecondClientSigned { get; set; }
        public byte[] Version { get; set; }
    }
}
