//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExchangeRequest()
        {
            this.TransactionsToBeSigneds = new HashSet<TransactionsToBeSigned>();
        }
    
        public string WalletAddress01 { get; set; }
        public string WalletAddress02 { get; set; }
        public string Asset01 { get; set; }
        public string Asset02 { get; set; }
        public Nullable<long> Amount01 { get; set; }
        public Nullable<long> Amount02 { get; set; }
        public string ServiceTransactionId { get; set; }
        public string ExchangeId { get; set; }
        public Nullable<long> FirstClientSigned { get; set; }
        public Nullable<long> SecondClientSigned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionsToBeSigned> TransactionsToBeSigneds { get; set; }
    }
}
