//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeOutput
    {
        public string TransactionId { get; set; }
        public long OutputNumber { get; set; }
        public long Amount { get; set; }
        public string PrivateKey { get; set; }
        public long Consumed { get; set; }
        public string Script { get; set; }
    }
}
