//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class LkeBlkChnMgrCoin
    {
        public string TransactionId { get; set; }
        public int OutputNumber { get; set; }
        public long SatoshiAmount { get; set; }
        public Nullable<long> AssetAmount { get; set; }
        public string AssetId { get; set; }
        public string SpentTransactionId { get; set; }
        public Nullable<int> SpentTransactionInputNumber { get; set; }
        public byte[] Version { get; set; }
    }
}
