//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class LkeBlkChnMgrTransactionsToBeSent
    {
        public string TransactionId { get; set; }
        public string TransactionHex { get; set; }
        public bool HasBeenSent { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool ShouldBeSent { get; set; }
        public string ReferenceNumber { get; set; }
        public byte[] Version { get; set; }
    }
}
