//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffchainChannel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OffchainChannel()
        {
            this.ChannelCoins = new HashSet<ChannelCoin>();
            this.MultisigChannels = new HashSet<MultisigChannel>();
            this.OffchainChannel1 = new HashSet<OffchainChannel>();
        }
    
        public long ChannelId { get; set; }
        public Nullable<long> ReplacedBy { get; set; }
        public string unsignedTransactionHash { get; set; }
        public byte[] Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelCoin> ChannelCoins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultisigChannel> MultisigChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffchainChannel> OffchainChannel1 { get; set; }
        public virtual OffchainChannel OffchainChannel2 { get; set; }
    }
}
