//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class PregeneratedReserve
    {
        public long id { get; set; }
        public string ReserveId { get; set; }
        public string PreGeneratedOutputTxId { get; set; }
        public int PreGeneratedOutputN { get; set; }
        public System.DateTime CreationTime { get; set; }
        public byte[] Version { get; set; }
    
        public virtual PreGeneratedOutput PreGeneratedOutput { get; set; }
    }
}
