//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundedOutput
    {
        public long id { get; set; }
        public string RefundedAddress { get; set; }
        public string RefundedTxId { get; set; }
        public int RefundedOutputNumber { get; set; }
        public long RefundTxId { get; set; }
        public bool HasBeenSpent { get; set; }
        public bool RefundInvalid { get; set; }
        public System.DateTime LockTime { get; set; }
        public byte[] Version { get; set; }
    
        public virtual RefundTransaction RefundTransaction { get; set; }
    }
}
