//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsWaitForConfirmation
    {
        public long id { get; set; }
        public string txToBeWatched { get; set; }
        public Nullable<long> WholeRefundId { get; set; }
        public Nullable<long> OldRefundedTxId { get; set; }
    
        public virtual RefundTransaction RefundTransaction { get; set; }
        public virtual WholeRefund WholeRefund { get; set; }
    }
}
