//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxBrdCstRequestDetail
    {
        public long Id { get; set; }
        public int RequestType { get; set; }
        public int RequestSource { get; set; }
        public string ReguestDetails { get; set; }
        public byte[] Version { get; set; }
    
        public virtual TxBrdCstRequestSource TxBrdCstRequestSource { get; set; }
        public virtual TxBrdCstRequestType TxBrdCstRequestType { get; set; }
    }
}
