//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnsignedTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnsignedTransaction()
        {
            this.UnsignedTransactions1 = new HashSet<UnsignedTransaction>();
            this.UnsignedTransactionSpentOutputs = new HashSet<UnsignedTransactionSpentOutput>();
        }
    
        public string TransactionHex { get; set; }
        public Nullable<bool> IsClientSignatureRequired { get; set; }
        public string ClientSignedTransaction { get; set; }
        public Nullable<bool> IsExchangeSignatureRequired { get; set; }
        public string ExchangeSignedTransactionAfterClient { get; set; }
        public string OwnerAddress { get; set; }
        public Nullable<bool> TransactionSendingSuccessful { get; set; }
        public string TransactionSendingError { get; set; }
        public string TransactionId { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<bool> HasTimedout { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> TransactionIdWhichMadeThisTransactionInvalid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnsignedTransaction> UnsignedTransactions1 { get; set; }
        public virtual UnsignedTransaction UnsignedTransaction1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnsignedTransactionSpentOutput> UnsignedTransactionSpentOutputs { get; set; }
    }
}
