//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnsignedTransactionSpentOutput
    {
        public string TransactionId { get; set; }
        public int OutputNumber { get; set; }
        public System.Guid UnsignedTransactionId { get; set; }
    
        public virtual UnsignedTransaction UnsignedTransaction { get; set; }
    }
}
