//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LykkeWalletServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class WholeRefund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WholeRefund()
        {
            this.WholeRefundSpentOutputs = new HashSet<WholeRefundSpentOutput>();
        }
    
        public long id { get; set; }
        public string BitcoinAddress { get; set; }
        public string TransactionHex { get; set; }
        public string TransactionId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LockTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WholeRefundSpentOutput> WholeRefundSpentOutputs { get; set; }
    }
}
