/****** Object:  Table [dbo].[SegKeys]    Script Date: 8/12/2016 8:47:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SegKeys](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[ClientPubKey] [varchar](130) NOT NULL,
	[ExchangePrivateKey] [varchar](52) NOT NULL,
 CONSTRAINT [PK_SegKeys] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
