/****** Object:  Table [dbo].[DBLog]    Script Date: 9/30/2016 8:33:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DBLog](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[Message] [text] NOT NULL,
	[CreationDate] [datetime] NOT NULL,
 CONSTRAINT [PK_DBLog] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


